apiVersion: apps/v1
kind: Deployment
metadata:
  name: gol-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gol-backend
  template:
    metadata:
      labels:
        app: gol-backend
    spec:
      containers:
        - name: gol-backend
          image: gol-backend:latest
          ports:
            - containerPort: 55000
          env:
            - name: PORT
              value: "55000"
---
apiVersion: v1
kind: Service
metadata:
  name: gol-backend
spec:
  type: ClusterIP
  selector:
    app: gol-backend
  ports:
    - port: 55000
      targetPort: 55000
